---
- name: Install pip3
  become: true
  when: ansible_os_family == "Debian"
  apt:
    name: python3-pip
    update_cache: true
    state: latest
  
- name: Install pipenv
  pip:
    name: pipenv
    executable: pip3
    extra_args: --user

- name: Check path for $HOME/.local/lib (Ubuntu)
  command: "awk /.local/ {{ ansible_env.HOME }}/.profile"
  register: check_path
  changed_when: False

- name: Update path (Ubuntu)
  when: (ansible_lsb['description'] == "Ubuntu 17.10") and
        (check_path.stdout is not undefined)
  blockinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    block: |
      if [ -d "$HOME/.local/bin" ] ; then
          PATH="$HOME/.local/bin:$PATH"
      fi


